persistence false
log_dest stdout
log_type error
log_type warning
log_type notice
connection_messages true
sys_interval 10

listener 9001
protocol websockets
socket_domain ipv4
listener_allow_anonymous false
password_file /run/secrets/mosquitto_passwords
acl_file /mosquitto/config/acl.production

max_connections 50
max_packet_size 16384
max_qos 1
max_inflight_messages 20
max_queued_messages 100
